service: giftmash

image: aronwolf/giftmash

servers:
  web:
    - 65.21.159.249

proxy:
  ssl: true
  host: giftmash.webcloudpower.com

# Credentials for your image host.
registry:
  username: aronwolf

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"


volumes:
  - "giftmash_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64
